/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fran.reporteformulario;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Francisco
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGuardar = new javax.swing.JButton();
        txtInspector = new javax.swing.JTextField();
        labelInspector = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listReport = new javax.swing.JList<>();
        labelEmailInsp = new javax.swing.JLabel();
        txtEmailInspector = new javax.swing.JTextField();
        labelCelInspect = new javax.swing.JLabel();
        txtCelInspector = new javax.swing.JTextField();
        labelConsorcio = new javax.swing.JLabel();
        txtConsorcio = new javax.swing.JTextField();
        labelTrabajador = new javax.swing.JLabel();
        txtTrabajador = new javax.swing.JTextField();
        labelCelTrabajador = new javax.swing.JLabel();
        txtCelTrabajador = new javax.swing.JTextField();
        bottonEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGuardar.setText("Guardar");
        buttonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGuardarActionPerformed(evt);
            }
        });

        labelInspector.setText("Inspector:");

        jScrollPane1.setViewportView(listReport);

        labelEmailInsp.setText("EmailInsp");

        labelCelInspect.setText("CelInspect");

        txtCelInspector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelInspectorActionPerformed(evt);
            }
        });

        labelConsorcio.setText("Consorcio");

        labelTrabajador.setText("Trabajador");

        txtTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTrabajadorActionPerformed(evt);
            }
        });

        labelCelTrabajador.setText("CelTrabaj");

        txtCelTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelTrabajadorActionPerformed(evt);
            }
        });

        bottonEliminar.setText("Eliminar");
        bottonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(512, Short.MAX_VALUE)
                .addComponent(bottonEliminar)
                .addGap(66, 66, 66))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelCelTrabajador)
                                .addGap(18, 18, 18)
                                .addComponent(txtCelTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelTrabajador)
                                .addGap(18, 18, 18)
                                .addComponent(txtTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelConsorcio)
                                .addGap(18, 18, 18)
                                .addComponent(txtConsorcio, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelCelInspect)
                                .addGap(18, 18, 18)
                                .addComponent(txtCelInspector, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelEmailInsp)
                                .addGap(18, 18, 18)
                                .addComponent(txtEmailInspector, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelInspector)
                                .addGap(18, 18, 18)
                                .addComponent(txtInspector, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(buttonGuardar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bottonEliminar)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelInspector)
                    .addComponent(txtInspector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmailInsp)
                    .addComponent(txtEmailInspector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCelInspect)
                    .addComponent(txtCelInspector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelConsorcio)
                    .addComponent(txtConsorcio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTrabajador)
                    .addComponent(txtTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCelTrabajador)
                    .addComponent(txtCelTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonGuardar)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCelInspectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelInspectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelInspectorActionPerformed

    private void txtTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTrabajadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTrabajadorActionPerformed

    private void txtCelTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelTrabajadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelTrabajadorActionPerformed

    
    List<ReportDto> listReportDto= new ArrayList<>();
    
    private void buttonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGuardarActionPerformed
        ReportDto dto= new ReportDto();
        dto.setInspector(this.txtInspector.getText());
        dto.setEmailInspector(this.txtEmailInspector.getText());
        dto.setCelInspector(this.txtCelInspector.getText());
        dto.setConsorcio(this.txtConsorcio.getText());
        dto.setTrabajador(this.txtTrabajador.getText());
        dto.setCelTrabajador(this.txtCelTrabajador.getText());
        
        listReportDto.add(dto);
        actualizarLista();        
        JOptionPane.showMessageDialog(rootPane, "Los Datos fueron guardados correctamente.");
        limpiarCajasTexto();
        
    }//GEN-LAST:event_buttonGuardarActionPerformed

    private void bottonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonEliminarActionPerformed
       
        
        int indice=this.listReport.getSelectedIndex();
        listReportDto.remove(indice);
        JOptionPane.showMessageDialog(rootPane, "Los Datos fueron eliminados correctamente.");
        actualizarLista();
    }//GEN-LAST:event_bottonEliminarActionPerformed

    private void actualizarLista(){
        DefaultListModel datos = new DefaultListModel();
        for(int i=0; i<listReportDto.size(); i++){
            ReportDto dto=listReportDto.get(i);
            datos.addElement(dto);
        }
        this.listReport.setModel(datos);
    
    }
    
    private void limpiarCajasTexto(){
    
        this.txtInspector.setText(" ");
        this.txtEmailInspector.setText(" ");
        this.txtCelInspector.setText(" ");
        this.txtConsorcio.setText(" ");
        this.txtTrabajador.setText(" ");
        this.txtCelTrabajador.setText(" ");
        
    }
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bottonEliminar;
    private javax.swing.JButton buttonGuardar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCelInspect;
    private javax.swing.JLabel labelCelTrabajador;
    private javax.swing.JLabel labelConsorcio;
    private javax.swing.JLabel labelEmailInsp;
    private javax.swing.JLabel labelInspector;
    private javax.swing.JLabel labelTrabajador;
    private javax.swing.JList<String> listReport;
    private javax.swing.JTextField txtCelInspector;
    private javax.swing.JTextField txtCelTrabajador;
    private javax.swing.JTextField txtConsorcio;
    private javax.swing.JTextField txtEmailInspector;
    private javax.swing.JTextField txtInspector;
    private javax.swing.JTextField txtTrabajador;
    // End of variables declaration//GEN-END:variables
}
